name = "cf-tunnel-watch"
main = "worker.js"
compatibility_date = "2025-10-01"

[triggers]
crons = ["*/1 * * * *"]   # toutes les minutes

# KV binding
[[kv_namespaces]]
binding = "STATE"
id = "dcc96446226949f29ba36e7f9ef9f213"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true
